---
abstract: 'Thrift Transport allowing Kerberos auth/encryption through GSSAPI'
author:
  - 'David Morel <david.morel@amakuru.net>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Thrift-SASL-Transport
requires:
  Data::Dumper: '0'
  Thrift::BinaryProtocol: '0'
  constant: '0'
  strict: '0'
  warnings: '0'
version: '0.003'
